# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-01 04:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_auto_20180612_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.Product', unique=True),
        ),
    ]
