# Generated by Django 4.0 on 2021-12-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_auto_20180701_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
