# Generated by Django 4.0 on 2021-12-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_product_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_qlt1_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='product_qlt2_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='product_qlt3_price',
            field=models.IntegerField(default=0),
        ),
    ]
