# Generated by Django 4.0 on 2021-12-28 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0006_product_product_qlt1_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cust_bill',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
