# Generated by Django 4.0 on 2021-12-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0007_remove_inventory_product_delete_cust_bill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
