# Generated by Django 4.0 on 2021-12-28 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0009_remove_product_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_email',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_idt',
            field=models.CharField(default='', max_length=7),
        ),
    ]
