# Generated by Django 4.0 on 2021-12-28 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0010_remove_customer_customer_email_customer_customer_idt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_qlt1_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_qlt2_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_qlt3_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
